(require 'color-theme)
(defun lothlorien ()
  (interactive)
  (color-theme-install
   '(lothlorien
      ((background-color . "#1d1b1b")
      (background-mode . light)
      (border-color . "#5a3f11")
      (cursor-color . "#aef971")
      (foreground-color . "#fcfcfc")
      (mouse-color . "black"))
     (fringe ((t (:background "#5a3f11"))))
     (mode-line ((t (:foreground "#ffffff" :background "#5b2710"))))
     (region ((t (:background "#de4a4a"))))
     (font-lock-builtin-face ((t (:foreground "#20cb24"))))
     (font-lock-comment-face ((t (:foreground "#91734b"))))
     (font-lock-function-name-face ((t (:foreground "#d34545"))))
     (font-lock-keyword-face ((t (:foreground "#9ed2ea"))))
     (font-lock-string-face ((t (:foreground "#c8c25b"))))
     (font-lock-type-face ((t (:foreground"#b246c8"))))
     (font-lock-variable-name-face ((t (:foreground "#fcfcfc"))))
     (minibuffer-prompt ((t (:foreground "#9fb9ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'lothlorien)
(color-theme-initialize)
(lothlorien)
